version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: prisma
    ports:
      - 5436:5432
    networks:
      - tuto-prisma
networks:
  tuto-prisma: